### ISSUE TITLE
Grammar and spell checking the README.md

### ISSUE THREAD

**Issue by RIAEvangelist** [RIAEvangelist/peacenotwar#1]
This module was written in just a couple of hours and I have a day job. Spelling is not my forte :) I speak too many languages.

**Comment by designdrop** [comment]
Submitted pull request with fixes

**Comment by RIAEvangelist** [comment]
@designdrop I just merged changes thanks! @sataylor7 thanks for checking this too, it is a big help.

changes will get published in the next release once we can get the correct messaging for #2
