### ISSUE TITLE
double standard

### ISSUE THREAD

**Issue by wbflike** [RIAEvangelist/peacenotwar#12]
![sb](https://user-images.githubusercontent.com/22762921/158559741-31f9c60a-8066-4002-ad2b-b9bfba212f01.jpg)
The United States is the country that wags the most wars

**Comment by nallath** [comment]
@wbflike https://en.wikipedia.org/wiki/Whataboutism && https://en.wikipedia.org/wiki/Tu_quoque

**Comment by micjax** [comment]
It's not really a case of "Russia acts like US but can't get away with it."

If you consider Afghanistan fiasco, you know that it's located in the middle of nowhere and US had no business committing war crimes there, yet they did. 

I'm Russian and from my perspective it's saddens that brainded liberals & liberal agenda are weaponized this way against us.

вы думаете это нам тут мозги промывают, так вот с каких пор это нормально нахуярится гормонов и быть "девушкой с хуем"?
