### ISSUE TITLE
not funny

### ISSUE THREAD

**Issue by lerrific** [RIAEvangelist/peacenotwar#18]
didn't laugh

**Comment by MichaelEpicA** [comment]
very good issue

**Comment by lerrific** [comment]
I only had 3 KB of space left on my drive and the 4.54 KB that this text file uses upon creation caused my computer to instantly EXPLODE.

**Comment by MichaelEpicA** [comment]
> I only had 3 KB of space left on my drive and the 4.54 KB that this text file uses upon creation caused my computer to instantly EXPLODE.

holy shit, intense programming 😎

**Comment by RIAEvangelist** [comment]
I remember when there was a Samsung battery issue and computers were actually exploding. That was super not funny!

Also, so sorry about the 4.54kb file size perhaps removing some of the languages could reduce it to a sub 3kb size. Can't make any promises though. Thanks for the notification.
