### ISSUE TITLE
With love from all mature developers

### ISSUE THREAD

**Issue by Kadeluxe** [RIAEvangelist/peacenotwar#20]

**Comment by MichaelEpicA** [comment]
man gets cancelled on github

**Comment by sssembler** [comment]
reported it to npm as malware being included in node-ipc for a start. not needed or wanted.

**Comment by Darkmift** [comment]
I can only hope you are extremely naive.
Your actions will not inspire peace and understanding....quite the opposite....your actions violated core trust and concensus within a community that uses NPM for its livelyhood.

I hope you will be held accountable and properly prosecuted for your actions as deterent for others.

**Comment by vncastanheira** [comment]
I'm reporting this garbage right now, imagine if he actually installed malware on our computer. 
Fucking crybaby sitting comfortable at his mom's basement thinking that is doing good to the world.

**Comment by majorendian** [comment]
Remember folks,

WITHOUT ANY WARRANTY, EXPRESS OR IMPLIED

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah, really stupid decision to break and endager things which don't have anything in common with russia, just based on IP. really dumb idea.

**Comment by wojtekpolska** [comment]
man thinks random people's computers are his blog where he can post his opinions. 
**i dont argue that the war is evil**, but this is damn not the place to do such stuff. you can share that on social media, youtube, email, etc. but not this way!

people everywhere are scared they got a virus cause strange files appear on their desktop, thousands of PC's were wiped cause thats what cautious people do after they get infected. people say that this even corrupted some databases. its just stupid. 

also it undermines trust in open-source software, and will make developers think twice, before deciding if they want to allow random people to contribute to their projects. 

Github is not a political forum. no matter if your opinions are "right" or "wrong", dont share them this way

**Comment by 1d0t** [comment]
>Remember folks,
>WITHOUT ANY WARRANTY, EXPRESS OR IMPLIED

A waiver of warranty would only cover accidental damage such as damage caused by bugs, it would not cover deliberate damage. You can't write malware and release it to the world and then waive all responsibility for it.
