### ISSUE TITLE
You're a dipshit

### ISSUE THREAD

**Issue by vncastanheira** [RIAEvangelist/peacenotwar#21]
I almost got scared that my computer was infected with malware because a retard like you did this.

**Comment by KyrXtz** [comment]
Protest against something by taking part in it ?
Smart.

**Comment by vncastanheira** [comment]
> Protest against something by taking part in it ? Smart.

Look man, do you like spreading malware on people's computer, that is why you're defending this?
I do not fucking care what he do to protest as long it doesn't having anything to do with infecting my computer. Go be a troll somewhere else, fucking basement dweller.

**Comment by vncastanheira** [comment]
Anyone reading this, please go to https://support.github.com/contact/report-abuse to help remove this repository.

**Comment by KyrXtz** [comment]
I wasn't particularly defending this, i was rather pointing out the fallacy in your statement.
Also watch your language this isn't your discord server channel.

**Comment by vncastanheira** [comment]
> I wasn't particularly defending this, i was rather pointing out the fallacy in your statement. Also watch your language this isn't your discord server channel.

Delete my comments if you're so offended. What a joke all of this is.

**Comment by vncastanheira** [comment]
> I wasn't particularly defending this, i was rather pointing out the fallacy in your statement. Also watch your language this isn't your discord server channel.

This whole thing is a joke.

**Comment by wojtekpolska** [comment]
There are places to put political statements, and there are places that they do not belong

users' desktops are the second one. 
this is (technically) a virus, since it appears on user's desktop without their knowledge nor permission. even tho its just a txt file, its not appropriate to do sth like this. 

it scares too many people, i just saw ppl posting online being scared "did i get a virus" etc.

**Comment by lewdogk** [comment]
> I almost got scared that my computer was infected with malware because a retard like you did this.

reported for abusive comments

**Comment by eglove** [comment]
Another embarrassment to open-source. I hope you get banned as well.

https://snyk.io/blog/peacenotwar-malicious-npm-node-ipc-package-vulnerability/

**Comment by imgrey** [comment]
You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.
