### ISSUE TITLE
I open unity hub v3.1.0 and it creates the file "WITH-LOVE-FROM-AMERICA.txt" 

### ISSUE THREAD

**Issue by luizfern12** [RIAEvangelist/peacenotwar#22]
I think that Unity Hub uses node-ipc and because node-ipc uses the peacenotwar module, Unity Hub creates the "WITH-LOVE-FROM-AMERICA.txt" file on desktop

**Comment by vncastanheira** [comment]
> I think that Unity Hub uses node-ipc and because node-ipc uses the peacenotwar module, Unity Hub creates the "WITH-LOVE-FROM-AMERICA.txt" file on desktop

You've been infected with malware by this guy, basically.

**Comment by AlexHolderDeveloper** [comment]
Hey @luizfern12 , there should be a hotfix for Unity Hub available shortly (if not right now) that hopefully prevents this package from being a nuisance. 

[https://unity3d.com/hub/whats-new](https://unity3d.com/hub/whats-new)

**Comment by majorendian** [comment]
"nuisence" is a weak word, it deletes peoples disks when you are in russia or ukraine or belarus

**Comment by sssembler** [comment]
they have been made aware and patched it out - they are now also looking at the lib as a whole, hopefully they do not use it going forward. Author fucked himself.
