### ISSUE TITLE
Good repo, but is a way to save face

### ISSUE THREAD

**Issue by SLCH** [RIAEvangelist/peacenotwar#25]
This repo is ok. There should not have been a war.

**Comment by vncastanheira** [comment]
This guy has a twitter account and instead of putting messages of support, he decides to disturb everyone with a sketchy and obscure file on your desktop.

**Comment by MichaelEpicA** [comment]
> This guy has a twitter account and instead of putting messages of support, he decides to disturb everyone with a sketchy and obscure file on your desktop.

very interesting way of spreading a message, that's for sure.
