### ISSUE TITLE
lmao cant believe the malding kekkkkkkk

### ISSUE THREAD

**Issue by lewdogk** [RIAEvangelist/peacenotwar#27]
hahahahaha holy cow man all these dudes out there former scrubs and skids who got kekkolded into wearing the business casual

get the f--- off the internet, this is still hacker country

aight peace

**Comment by lewdogk** [comment]
imaginig some corpo drone having to explain to his boss why his dependency management software is trying to hack russia lmfaoooooooo im ded fam

**Comment by lewdogk** [comment]
some desiccated-ass calvinist sam walton lookin bro makin appeals to _professionalism_ on linkedin i see u 👀

**Comment by VitAndrGuid** [comment]
@lewdogk 
![image](https://user-images.githubusercontent.com/47070525/158721588-12819f4d-2501-4bf4-bfc9-718ecc416d48.png)

**Comment by lewdogk** [comment]
@VitAndrGuid please do not doxx me

**Comment by lewdogk** [comment]
W-well, this is me 👉👈

![image](https://user-images.githubusercontent.com/50758026/158726202-411f71af-354f-4a95-a31d-5596ca536684.png)
