### ISSUE TITLE
Start a cyberwar against US, Germany, Japan, etc

### ISSUE THREAD

**Issue by 0loli** [RIAEvangelist/peacenotwar#28]
because they killed millions

**Comment by MichaelEpicA** [comment]
bruh what? That is the dumbest idea I have heard of

**Comment by 0loli** [comment]
> bruh what? That is the dumbest idea I have heard of

Why? Because this is USA?

**Comment by lewdogk** [comment]
- [x] based
- [x] redpilled

**Comment by MichaelEpicA** [comment]
> > bruh what? That is the dumbest idea I have heard of
> 
> Why? Because this is the USA?

No, it's because legit that's history, it happened in the past, doesn't mean you go after them now. Jesus Christ, what is this. Twitter?

**Comment by 0loli** [comment]
bruh I don't want to explain anything to braindead americans. Praise your president and US war veterans.

**Comment by MichaelEpicA** [comment]
> bruh I don't want to explain anything to braindead americans. Praise your president and US war veterans.

... none of us want war right now.

**Comment by 0loli** [comment]
> > bruh I don't want to explain anything to braindead americans. Praise your president and US war veterans.
> 
> ... none of us want war right now.

I want a war against the US.

**Comment by MichaelEpicA** [comment]
> > > bruh I don't want to explain anything to braindead americans. Praise your president and US war veterans.
> > 
> > 
> > ... none of us want war right now.
> 
> I want a war against the US.

seriously? Why?

**Comment by 0loli** [comment]
> > > > bruh I don't want to explain anything to braindead americans. Praise your president and US war veterans.
> > > 
> > > 
> > > ... none of us want war right now.
> > 
> > 
> > I want a war against the US.
> 
> seriously? Why?

You know why

**Comment by MichaelEpicA** [comment]
> >
No, no I really dont. America hasn't done anything wrong recently that deserves a war.

**Comment by lewdogk** [comment]
> No, no I really dont. America hasn't done anything wrong recently that deserves a war.
This is your brain on normie media

**Comment by MichaelEpicA** [comment]
> > No, no I really dont. America hasn't done anything wrong recently that deserves a war.
> 
> This is your brain on normie media

this is github, why does this even belong here

**Comment by lewdogk** [comment]
> this is github, why does this even belong here

meh idk tbh maybe that's a fair point maybe not but look bro, look, peeps will trust implicitly code written by unemployed schizos who write mods for 18+ games to impress chicks on furaffinity and then have the audacity to get mad when it inevitably blows up in their face like.... bruhhh...

that's all im tryna say

**Comment by danisztls** [comment]
I guess I opened 4chan by mistake.

**Comment by MichaelEpicA** [comment]
> I guess I opened 4chan by mistake.

yeah, pretty fricken much.

**Comment by Tvde1** [comment]
Just going after Russia is kinda lame. Instead of linking Whataboutism when asked about USA's wars, why don't you apply this trick to US' IPs as well? Show us you have balls

**Comment by callmedarkfried** [comment]
yea chief idk if you noticed but there was this thing a couple years back after germany and Japan decided to commit genocide and it went a little like this:

they got bombed to pieces.

thats about it, thats the story. Japan even had a couple cities vaporised, you should really look it up its quite a niche piece of trivia, this.

**Comment by dartzcn** [comment]
>>> bruh I don't want to explain anything to braindead americans. Praise your president and US war veterans.

>> ... none of us want war right now.

> I want a war against the US.

You're calling for a war which will undoubtedly result in the deaths of hundreds of millions of people across the globe because a mean soyboy overwrote your files? lol
