### ISSUE TITLE
use firejail :P 

### ISSUE THREAD

**Issue by 0loli** [RIAEvangelist/peacenotwar#29]
Firejail is a cool tool to prevent applications from accessing files they generally should not. Disallow accessing the network or tunnel traffic.

The current malware in this repo is fully useless if you run it inside a firejail with limited access to files. For example with --private=. or --read-only="*", so @RIAEvangelist can suck your dick!

More info: `man firejail`

**Comment by MichaelEpicA** [comment]
there isnt even malware in this repo, there's malware in node-ipc, and its been shown by commits that it appears to have been removed. this repo does exactly what it does on the tin.
