### ISSUE TITLE
Issue #1

### ISSUE THREAD

**Issue by MichaelEpicA** [RIAEvangelist/peacenotwar#30]
Yeah, it seems like this repo has been spammed with Issues which aren't even issues, just political crap. lovely

**Comment by lewdogk** [comment]
damn... u right...

**Comment by vncastanheira** [comment]
Oh geez, we wonder why...

**Comment by MichaelEpicA** [comment]
ive lost all braincells thanks to this shit

**Comment by jjdub7** [comment]
> Yeah, it seems like this repo has been spammed with Issues which aren't even issues, just political crap. lovely

Political crap repo attracts political crap discussion

> shocked pikachu face
