### ISSUE TITLE
An anti-war message

### ISSUE THREAD

**Issue by brandon-lockaby** [RIAEvangelist/peacenotwar#34]
I have been reading the discourse, trying to understand what it's about, and I'm not sure if the most malicious part was ever even live or not... but...

Why "WITH-LOVE-FROM-AMERICA.txt?"  It seems to create the appearance of an attack and attribute it to America, and I can't see that provoking anything but confused anger toward America in the shock of finding that file.  An affected user might exclaim, "America is hacking our computers?"

Why not a more region-agnostic anti-war message?  Something like "peace-not-war.txt?"

**Comment by Mause** [comment]
Honestly, most people in the world don't exactly view America as a source of peace, so while well intended, the filename should probably be changed

**Comment by imgrey** [comment]
You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.

**Comment by RIAEvangelist** [comment]
@brandon-lockaby fair point. I named it that because of [with love from russia](https://www.imdb.com/title/tt0057076/)
