### ISSUE TITLE
Russian malware modules: 0, Nazi lover malware module: yet another

### ISSUE THREAD

**Issue by rowaasr13** [RIAEvangelist/peacenotwar#36]
Makes you think.
Also enjoy you report, Nazi collaborator.

Your beloved Nazi bombed Donetsk on 14th March with Tochka-U (https://en.wikipedia.org/wiki/OTR-21_Tochka) in the middle of the day, explicitly targeting center of the city in the middle of business day, with reports day before of several Telegram channels injecting fake calls to meetings in that location . 20+ dead, tons of injured, including kids.

Look with your shitty nazi-loving eyes at those:
https://t.me/boris_rozhin/32250
https://t.me/boris_rozhin/32255
https://t.me/boris_rozhin/32256
https://t.me/boris_rozhin/32265
https://t.me/RtrDonetsk/3401
https://t.me/boris_rozhin/32296

Did your rotten heart bleed for them? No, your piece of shit heart only bleeds for those you feel close to you - Ukro-Nazi military.

Your Western insane toilet newspapers gone as far as use several photos from this terror act as illustration for Russian strikes against military bases:
https://twitter.com/ABC/status/1503495384970272769

Rot in hell, scum.

**Comment by AntonGrekov** [comment]
@rowaasr13 Can you please help find a way to report author or repository or both ? I can't find where a report form is located

**Comment by denis-g** [comment]
usu this
https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam

**Comment by rowaasr13** [comment]
GitHub:
https://support.github.com/contact/report-abuse > Harmful code > Malware

NPM:
https://www.npmjs.com/support?inquire=security&security-inquire=malware&package=node-ipc

Feel free to send relevant .js file from commit to all the anti-virus and anti-malware support addresses you know as well.
