### ISSUE TITLE
REPORT THIS REPO. IT SERVERS ONE PURPOSE. IT PROVIDES DELETE ALL YOUR FILES FUNCTIONALITY FOR OTHER MALWARE REPOS

### ISSUE THREAD

**Issue by AntonGrekov** [RIAEvangelist/peacenotwar#37]
REPORT THIS REPO. IT SERVERS ONE PURPOSE. IT PROVIDES DELETE ALL YOUR FILES FUNCTIONALITY FOR OTHER MALWARE REPOS !!
REPORT THIS REPO. IT SERVERS ONE PURPOSE. IT PROVIDES DELETE ALL YOUR FILES FUNCTIONALITY FOR OTHER MALWARE REPOS !!
REPORT THIS REPO. IT SERVERS ONE PURPOSE. IT PROVIDES DELETE ALL YOUR FILES FUNCTIONALITY FOR OTHER MALWARE REPOS !!

**Comment by imgrey** [comment]
I'm glad it worked.
You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.

**Comment by DarkOutX** [comment]
> I'm glad it worked. You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.

\>Supports idea of dangerous-code with condition ONLY for russian common people
\>Calls russians nazis

Are you ok, lol?

**Comment by imgrey** [comment]
> > I'm glad it worked. You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.
> 
> >Supports idea of dangerous-code with condition ONLY against russian common people >Calls russians nazis
> 
> Are you ok, lol?

I'm not ok. Russian nazi destroy peaceful cities at this very moment.
Ukraine was peaceful before ruso-nazi invaded. We never had ANY terror attacks, no conflicts.

It should be obvious I am not "ok".

**Comment by suslovsergey** [comment]
диванные войска хохляндии повылезаои :-D

**Comment by wojtekpolska** [comment]
@imgrey do u even know the meaning of the word "nazism" ?

**Comment by imgrey** [comment]
> @imgrey do u even know the meaning of the word "nazism" ?

https://youtu.be/J2cdVCtGOoI

Russian fascists did that.
It is a swear word they will be unable to clear off.

**Comment by imgrey** [comment]
> диванные войска хохляндии повылезали :-D

### **Пошел нахуй пидар ебаный.**

Так понятно ? Дерьма кусок.

**Comment by wojtekpolska** [comment]
@imgrey https://en.wikipedia.org/wiki/Nazism while i agree russians are evil, i dont think you are using the word correctly.

**Comment by rupower** [comment]
> > диванные войска хохляндии повылезали :-D
> 
> ### **Пошел нахуй пидар ебаный.**
> Так понятно ? Дерьма кусок.

У тебя пена со рта лезет, иди вытрись об русский танк)))

**Comment by VladimirPchelko** [comment]
Ha ha

**Comment by VladimirPchelko** [comment]
Hope many Russian servers where fucked
