### ISSUE TITLE
go to hell your fucking american idiot

### ISSUE THREAD

**Issue by mharry32** [RIAEvangelist/peacenotwar#38]
go to hell your fucking american idiot

**Comment by imgrey** [comment]
You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.

**Comment by frct1** [comment]
> 

Lol, who said that ? Some old guy who working for 2 sides ?
Do you remember actions what USA did in Asia ?

**Comment by userbig** [comment]
@frct1 this is not an excuse to commit genocide, fam.

**Comment by frct1** [comment]
> @frct1 this is not an excuse to commit genocide, fam.

Hey, is't not an a excuse. Just open eyes, world only talking what needed to talk. Nobody asked US when they bombed Asian countries. Any sanctions ? Oh, i forgot, it's another thing and not related to this.

West world fucked-up when they introduced sanctions against regular people. It's worked but in another direction :)

**Comment by imgrey** [comment]
> > @frct1 this is not an excuse to commit genocide, fam.
> 
> Hey, is't not an a excuse. Just open eyes, world only talking what needed to talk. Nobody asked US when they bombed Asian countries. Any sanctions ? Oh, i forgot, it's another thing and not related to this.
> 
> West world fucked-up when they introduced sanctions against regular people. It's worked but in another direction :)

You are bloody immoral russian terrorist. Do you really think war crimes in past is the reason you are allowed to do your own war crimes ?

You are miserable failures. Just poor idiots really.

**Comment by frct1** [comment]
> You are bloody immoral russian terrorist. Do you really think war crimes in past is the reason you are allowed to do your own war crimes ?
> 
> You are miserable failures. Just poor idiots really.

I understand that you can only talk with other people's words. What about your own opinion ? Where you was before ?
Just another rusofobic kid

**Comment by imgrey** [comment]
> > You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.
> 
> Lol, who said that ? Some old guy who working for 2 sides ? Do you remember actions what USA did in Asia ?

Bloody hypicrite. USA has NOTHING to do to your war crimes.
You miserable poor soviet retard.

**Comment by frct1** [comment]
> > > You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.
> > 
> > 
> > Lol, who said that ? Some old guy who working for 2 sides ? Do you remember actions what USA did in Asia ?
> 
> Bloody hypicrite. USA has NOTHING to do to your war crimes. You miserable poor soviet retard.

Hypocrite ? Probably. Only after moment when world started to talk shit like you :)
World can't even get that sanctions are helping to Russian government. Even your messages are showing stupid position of west countries without any objective meanings.

**Comment by imgrey** [comment]
> 

.

**Comment by JustAGod1** [comment]
> > > Can you just explain why me a poor usual student in Russia who have no power to make any differences in country should suffer from hate in the internet. I can understand when politics make sanctions against country. I used to such ignorance of my needs from my government. But when usual people do such things it looks like nationalism for me. I'm bad person and have to suffer just because Putin still exists.
> > > But still I've participated in each meeting arranged by our opposition. But now the whole world hates my nation and me in particular for the decision I haven't made. I have no money to immigrate from my country. I have no power to make any difference. But for the whole world I'm bloody ruso-nazi and bloody immoral russian terrorist. And everybody tries to make my life even harder than it is. My life and not the government's life.
> > 
> > 
> > don't make excuses to these brainwashed zombies who just watched their Russophobic TV
> 
> I will write the language you understand.
> 
> ### **Пошел нахер пидар ебаный.**
> Зверства ваших орков: https://youtu.be/J2cdVCtGOoI
> 
> Не будет вам прощения гниды.

Now everybody can clearly see that nazi here is you. You're trying to blame a whole nation wheres only one person who made a decision. 

I haven't insult you even once but you have just because I'm russian.

**Comment by imgrey** [comment]
> > You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.
> 
> Can you just explain why me a poor usual student in Russia who have no power to make any differences in country should suffer from hate in the internet. I can understand when politics make sanctions against country. I used to such ignorance of my needs from my government. But when usual people do such things it looks like nationalism for me. I'm bad person and have to suffer just because Putin still exists.
> 
> But still I've participated in each meeting arranged by our opposition. But now the whole world hates my nation and me in particular for the decision I haven't made. I have no money to immigrate from my country. I have no power to make any difference. But for the whole world I'm bloody ruso-nazi and bloody immoral russian terrorist. And everybody tries to make my life even harder than it is. My life and not the government's life.

We Ukrainians defended our freedom on Maidan. When it was -20 at night. They killed us with rifles. They thrown grenades, but we won.

You sit on your bottom and watch how your maniac destroys neighbor country. Newborn babies die from bleedings and  dehydration as your retards blocked city of Mariupol.

https://youtu.be/J2cdVCtGOoI

You do not have a moral right to open your mouth now.

**Comment by JustAGod1** [comment]
> > > You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.
> > 
> > 
> > Can you just explain why me a poor usual student in Russia who have no power to make any differences in country should suffer from hate in the internet. I can understand when politics make sanctions against country. I used to such ignorance of my needs from my government. But when usual people do such things it looks like nationalism for me. I'm bad person and have to suffer just because Putin still exists.
> > But still I've participated in each meeting arranged by our opposition. But now the whole world hates my nation and me in particular for the decision I haven't made. I have no money to immigrate from my country. I have no power to make any difference. But for the whole world I'm bloody ruso-nazi and bloody immoral russian terrorist. And everybody tries to make my life even harder than it is. My life and not the government's life.
> 
> We Ukrainians defended our freedom on Maidan. When it was -20 at night. They killed us with rifles. They thrown grenades, but we won.
> 
> You sit on your bottom and watch how your maniac destroys neighbor country. Newborn babies die from bleedings and dehydration as your retards blocked city of Mariupol.
> 
> https://youtu.be/J2cdVCtGOoI
> 
> You do not have a moral right to open your mouth now.

So you Ukrainians defend your freedom it's certainly a great thing. But now you propose to us to fight against regime of the country that can conquer Ukraine? Russia was preparing to any kind of Maidan for years. I live in the center of the Saint-Petersburg and here you can find a police squad each 100 meters. But we still fighting. 

We're doing our part to prevent russian evasion. And I think some russian people(not russian government) deserves thanks from Ukrainian people. A lot of our people are now in jail for protesting. A lot of our people was beaten. 

I have all rights to open my mouth.

**Comment by imgrey** [comment]
> > > > You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.
> > > 
> > > 
> > > Can you just explain why me a poor usual student in Russia who have no power to make any differences in country should suffer from hate in the internet. I can understand when politics make sanctions against country. I used to such ignorance of my needs from my government. But when usual people do such things it looks like nationalism for me. I'm bad person and have to suffer just because Putin still exists.
> > > But still I've participated in each meeting arranged by our opposition. But now the whole world hates my nation and me in particular for the decision I haven't made. I have no money to immigrate from my country. I have no power to make any difference. But for the whole world I'm bloody ruso-nazi and bloody immoral russian terrorist. And everybody tries to make my life even harder than it is. My life and not the government's life.
> > 
> > 
> > We Ukrainians defended our freedom on Maidan. When it was -20 at night. They killed us with rifles. They thrown grenades, but we won.
> > You sit on your bottom and watch how your maniac destroys neighbor country. Newborn babies die from bleedings and dehydration as your retards blocked city of Mariupol.
> > https://youtu.be/J2cdVCtGOoI
> > You do not have a moral right to open your mouth now.
> 
> So you Ukrainians defend your freedom it's certainly a great thing. But now you propose to us to fight against regime of the country that can conquer Ukraine? Russia was preparing to any kind of Maidan for years. I live in the center of the Saint-Petersburg and here you can find a police squad each 100 meters. But we still fighting.
> 
> We're doing our part to prevent russian evasion. And I think some russian people(not russian government) deserves thanks from Ukrainian people. A lot of our people are now in jail for protesting. A lot of our people was beaten.
> 
> I have all rights to open my mouth.

Иди в след за русским военным кораблем.

**Comment by Kadeluxe** [comment]
> > > You are real russian fascists. All the world hates you bloody ruso-nazi. You are war criminals.
> > 
> > 
> > Can you just explain why me a poor usual student in Russia who have no power to make any differences in country should suffer from hate in the internet. I can understand when politics make sanctions against country. I used to such ignorance of my needs from my government. But when usual people do such things it looks like nationalism for me. I'm bad person and have to suffer just because Putin still exists.
> > But still I've participated in each meeting arranged by our opposition. But now the whole world hates my nation and me in particular for the decision I haven't made. I have no money to immigrate from my country. I have no power to make any difference. But for the whole world I'm bloody ruso-nazi and bloody immoral russian terrorist. And everybody tries to make my life even harder than it is. My life and not the government's life.
> 
> We Ukrainians defended our freedom on Maidan. When it was -20 at night. They killed us with rifles. They thrown grenades, but we won.
> 
> You sit on your bottom and watch how your maniac destroys neighbor country. Newborn babies die from bleedings and dehydration as your retards blocked city of Mariupol.
> 
> https://youtu.be/J2cdVCtGOoI
> 
> You do not have a moral right to open your mouth now.

Jesus butthurt is real here xD

**Comment by rupower** [comment]
> I will write the language you understand.
> 
> ### **Пошел нахер пидар ебаный.**
> Зверства ваших орков: https://youtu.be/J2cdVCtGOoI
> 
> Не будет вам прощения гниды.

Нахрен мне твоё прощение, долбоёб? Иди лучше попроси прощения на аллее ангелов в Донецке. Или просто уебись об стену. Тупая шлюха

**Comment by EvilistMonkey** [comment]
> > > @frct1 this is not an excuse to commit genocide, fam.
> > 
> > 
> > Hey, is't not an a excuse. Just open eyes, world only talking what needed to talk. Nobody asked US when they bombed Asian countries. Any sanctions ? Oh, i forgot, it's another thing and not related to this.
> > West world fucked-up when they introduced sanctions against regular people. It's worked but in another direction :)
> 
> You are bloody immoral russian terrorist. Do you really think war crimes in past is the reason you are allowed to do your own war crimes ?
> 
> You are miserable failures. Just poor idiots really.

MORON.
