### ISSUE TITLE
Fuck you

### ISSUE THREAD

**Issue by lx30011** [RIAEvangelist/peacenotwar#39]

**Comment by imgrey** [comment]
You are real russian fascists. Report all 60 million ukrainians now. 
All the world hates you bloody ruso-nazi. You are war criminals.

**Comment by CdSy** [comment]
> You are real russian fascists. Report all 60 million ukrainians now. All the world hates you bloody ruso-nazi. You are war criminals.

Why not 60 billion? Be more boldly, the whole world with you and you can draw at least a trillion!

**Comment by Kadeluxe** [comment]
> You are real russian fascists. Report all 60 million ukrainians now. All the world hates you bloody ruso-nazi. You are war criminals.

lmao did you really just decide to spam this everywhere

**Comment by imgrey** [comment]
> 

Visit Mariupol. I will see how you laugh, you retard.

**Comment by Kadeluxe** [comment]
> Visit Mariupol. I will see how you laugh, you retard.

Hello? What's your point lol 
Did you just discover that there are WARS around the globe? Pathetic.

**Comment by imgrey** [comment]
> > Visit Mariupol. I will see how you laugh, you retard.
> 
> Hello? What's your point lol Did you just discover that there are WARS around the globe? Pathetic.

What you are saying IS:
- my life is not important
- life of my family is not important
- you don't care

Actually you are miserable russian retard.

**Comment by CdSy** [comment]
> Visit Mariupol. I will see how you laugh, you retard.

Thanks for this attractive offer but no. the Nazis of "Azov" will not let you go back from there. Wait, do you write from a cauldron? I see your desperation.

**Comment by pa3py6aka** [comment]
> All the world hates you bloody ruso-nazi. You are war criminals.

USA and European Union are not all world. Just stop watching your TV and turn on your own brains. 
![image](https://user-images.githubusercontent.com/12895355/158841395-91796cf9-9549-4f01-a0fa-52418e03fd4b.png)

**Comment by Kadeluxe** [comment]
@imgrey 
> > > Visit Mariupol. I will see how you laugh, you retard.
> > 
> > 
> > Hello? What's your point lol Did you just discover that there are WARS around the globe? Pathetic.
> 
> What you are saying IS:
> bla-bla-bla

What I'm saying is that HERE ON GITHUB I don't f care about Ukraine, Russia, USA, Iraq or whatever.
The problem HERE is not about wars or UA/RU relations, it's about NODE DEPENDENCY MANAGEMENT once again.
If you want to cry about WARS then go cry on Reddit or Facebook or wherever you want, Github is for SOFTWARE DEVELOPMENT and so is NPM. 
We, developers, work TOGETHER to make world better, and we don't make world better by CRYING about wars on Github and sabotaging NPM packages.
Is it really a hard concept for you to understand??

**Comment by imgrey** [comment]
> > All the world hates you bloody ruso-nazi. You are war criminals.
> 
> USA and European Union are not all world. Just stop watching your TV and turn on your own brains. ![image](https://user-images.githubusercontent.com/12895355/158841395-91796cf9-9549-4f01-a0fa-52418e03fd4b.png)

Вот что твои сограждане сделали в Мариуполе.

https://youtu.be/J2cdVCtGOoI

> ### **Иди нахер ебаный пидарас.**

**Comment by imgrey** [comment]
> @imgrey
> 
> > > > Visit Mariupol. I will see how you laugh, you retard.
> > > 
> > > 
> > > Hello? What's your point lol Did you just discover that there are WARS around the globe? Pathetic.
> > 
> > 
> > What you are saying IS:
> > bla-bla-bla
> 
> What I'm saying is that HERE ON GITHUB I don't f care about Ukraine, Russia, USA, Iraq or whatever. The problem HERE is not about wars or UA/RU relations, it's about NODE DEPENDENCY MANAGEMENT once again. If you want to cry about WARS then go cry on Reddit or Facebook or wherever you want, Github is for SOFTWARE DEVELOPMENT and so is NPM. We, developers, work TOGETHER to make world better, and we don't make world better by CRYING about wars on Github and sabotaging NPM packages. Is it really a hard concept for you to understand??

Пошел нахуй, дерьмо рашистское.

**Comment by Kadeluxe** [comment]
> > @imgrey
> > > > > Visit Mariupol. I will see how you laugh, you retard.
> > > > 
> > > > 
> > > > Hello? What's your point lol Did you just discover that there are WARS around the globe? Pathetic.
> > > 
> > > 
> > > What you are saying IS:
> > > bla-bla-bla
> > 
> > 
> > What I'm saying is that HERE ON GITHUB I don't f care about Ukraine, Russia, USA, Iraq or whatever. The problem HERE is not about wars or UA/RU relations, it's about NODE DEPENDENCY MANAGEMENT once again. If you want to cry about WARS then go cry on Reddit or Facebook or wherever you want, Github is for SOFTWARE DEVELOPMENT and so is NPM. We, developers, work TOGETHER to make world better, and we don't make world better by CRYING about wars on Github and sabotaging NPM packages. Is it really a hard concept for you to understand??
> 
> Пошел нахуй, дерьмо рашистское.

Wait, are you from Russia or Ukraine lol?? Why do you write in Russian? This is even more hilarious, you should FIGHT and DEFEND your country and you choose to spam the forums instead xD

**Comment by Aspie96** [comment]
> You are real russian fascists. Report all 60 million ukrainians now.

@imgrey and how does malware help the situation?
