### ISSUE TITLE
OF COURSE, THE BOMBING OF YUGOSLAVIA AT THE HEAD OF WHICH THE DICTATOR GIVES THE RIGHT TO BOMB DEMOCRATIC UKRAINE

### ISSUE THREAD

**Issue by Borowing** [RIAEvangelist/peacenotwar#44]
what about 8 years of bombing donbass? look at donetsk and luhansk right now, and compare it with harkiv and kyiv  right now

**Comment by pa3py6aka** [comment]
yes, if i will throw 3 bombs on Donetsk, instead of 50 bombs in Harkiv, i am sweet child and angel.

**Comment by Borowing** [comment]
yeah, 3 bombs at donetsk and a lot more in avdiivka

**Comment by rupower** [comment]
Ukrainian troops killed 14,000 civilians in Donbass. What you can say about it?

**Comment by Borowing** [comment]
> Ukrainian troops killed 14,000 civilians in Donbass. What you can say about it?

yeah, donbass was fully occupied by Ukraine, the same as kosovo

**Comment by hazNdaLQF2ZZnoQZdzBW** [comment]
@idrizp 
> There was an ethnic cleansing attempt on Kosovo, actually. 800,000 Kosovo Albanians were displaced. Not comparable.

What ethnic cleansing? [Wikipedia](https://en.wikipedia.org/wiki/Kosovo_War):

> However, estimates showed that prior to the bombing campaign on 24 March 1999, approximately 1,800 civilians had been killed in the Kosovo war, mostly Albanians but also Serbs and that there had been **no evidence of genocide or ethnic cleansing.**
