### ISSUE TITLE
You have no right to call yourself a developer after that.

### ISSUE THREAD

**Issue by ap10111997** [RIAEvangelist/peacenotwar#46]
You can't wash off this filth anymore

**Comment by ap10111997** [comment]
@sokil  Note that this is not from Russian television

**Comment by ap10111997** [comment]
@sokil  You didn't watch the video. It's 40 minutes long. You don't want to accept information that doesn't coincide with your opinion.  I have nothing more to say to you.

**Comment by ap10111997** [comment]
And for those who are still looking in here. Check out who the man is and other interviews with him. You will learn a lot of interesting things about this situation. We are ALL under the influence of the information war and we need to get to the bottom of the situation first.

**Comment by ap10111997** [comment]
@sokil Notice I didn't insult you.

**Comment by BANOnotIT** [comment]
@ap10111997 
> Then watch these videos and think about it.

The video is dated on 25 feb. Situation changed dramatically. It's not relevant at the moment.

> Our military is trying to save civilians. Look at the situation from the other side and get out of your information bubble.

Save civilians from how? Don't you think it's their own business to solve their problems? It's like we don't like when Obama shitting in our entrances and affect our politics but we somehow got the right to solve other countries' problems by our military forces?..

**Comment by ap10111997** [comment]
Constructive Dialogue. You don't know what it was like in Russia when Hitler's army invaded. The same people are now in Ukraine. I've seen many videos of people in Ukrainian army garb mimicking the German army of 1939 with gestures (Hand up). Many videos of them holding flags with swastikas. These people were turned against the Russians (Moskal). These videos were created after 2014. According to this Russian president was against Ukraine joining NATO. Then they would have any weapons available to them. Please remember the distance from the Ukrainian border to Moscow.

The civilians of any country should not suffer! Here I agree with you. Russia has provided humanitarian corridors in Mariupol, but civilians are simply not allowed out by the military. They are hiding behind them like a "human shield".

I am not claiming that Ukraine may have attacked Russia in the future, we will never know. Perhaps our president really was left with no other way to solve this problem.

Google what has been going on in the Donbass all these years - the key words are "Angel Alley." It was done by the Ukrainian military. These are the people we are trying to protect ourselves from. We are not going to occupy or conquer Ukraine.

**Comment by sokil** [comment]
@ap10111997 you need to switch off you tv and youtube propagandists and will you see another world. remove the foil cap. something tells me that you are also against vaccination)

**Comment by Borowing** [comment]
@ap10111997 If there are russian tanks in my town, that want to occupy my town how should react I?

**Comment by ap10111997** [comment]
They will not touch civilians. I understand that this is great fear and stress, and I am against suffering on the part of peaceful people. Humanitarian corridors are being created in the cities. Apparently, you have to endure this difficult time like everyone else...

**Comment by sokil** [comment]
@ap10111997 where are you from? For phrase "They will not touch civilians" - this means that @ap10111997 is a russian fake. 

Розмову з цим ботом пропоную закривати

**Comment by ap10111997** [comment]
I haven't seen a single constructive argument from you. If you think you are right, then prove it, be a man after all. No emotion.

**Comment by ap10111997** [comment]
@sokil  Also in your posts there are noticeably too many "Key Words" from the beginning of the dialogue. And your last post shows your utter helplessness. That's why you and I won't be able to communicate)

**Comment by Borowing** [comment]
> They will not touch civilians. I understand that this is great fear and stress, and I am against suffering on the part of peaceful people. Humanitarian corridors are being created in the cities. Apparently, you have to endure this difficult time like everyone else...

they touch civilians a lot more than militants, and anyway, I don't want to live on occupation by an authoritarian country, thanks!

**Comment by ap10111997** [comment]
I think a lot of people will draw conclusions for themselves.
https://www.youtube.com/channel/UC8vl-y5ldhs-XFisSKFdp1g/featured
I don't know what it is about people's reflection. 2017
0:25 - Бий москаля складайте трупы. Who really needs to - will translate.
They have been turned against the Russians all these years. Note that this is a chant and it's not the military

**Comment by sokil** [comment]
https://www.facebook.com/profile.php?id=100001529064638

This is Asher Joseph Cherkasky, he is jewish and he is soldier in Ukrainian army. He currently with his son fights for freedom of Ukraine against russia occupants.

![FB](https://user-images.githubusercontent.com/1829948/158882966-7a1d5407-b0c2-48f5-895e-ea0162746ce2.jpg)

This closes question about ukrainian nazis.

On this photo he takes two sisters that survived after bombing of Mariupol by russian aviation

![FB_IMG_1647546382141](https://user-images.githubusercontent.com/1829948/158883622-47d6e30b-fb53-4d84-8341-a9fae906e006.jpg)

This closes questions about "They will not touch civilians"

This grandfather is Ivan Zakujny. He is World War II veteran, and he takes medal of his grandsun, killed by russians when protecting ukrainian Donbas.

![image](https://user-images.githubusercontent.com/1829948/158884375-ec123d48-d2e7-4991-9ad2-90f8d1959dab.jpg)

This closes 
This is photo of attack on tv tower in Kyiv. 5 civils dead.  One of missles fall into memorial of Holicost on tombs of jewishs and ukrainians killed by nazi. 

![FMxgguYXoAAvigI](https://user-images.githubusercontent.com/1829948/158884687-5ebbca67-458c-4644-bf1f-087cfb027e87.jpeg)

This is Mariopol theatre where cilils was hide from russian bombs. There are big words writen on ground ДЕТИ - children. It was bombed yesterday.


![f7c680c-apuyuhlgf5krxnmvkul5nvjvay](https://user-images.githubusercontent.com/1829948/158885387-dd162df4-ab4f-4b4f-b049-441af0799632.jpg)


This building is bear the place where im livind. One kid dead 
![novi-petrivczi-300x169](https://user-images.githubusercontent.com/1829948/158885781-63fafd85-6e36-4f3e-bfb1-697645382687.png)

Now you may told that this is fakes, or provocations of ukrainians, but truth is simple: russian nazi reich will be destroyed by united democracy world.

**Comment by ap10111997** [comment]
You're trying to push emotion, to sting. Why else would there be pictures here? I, too, can drop a lot of pictures of the children of Donbass.

With you, @sokil, I do not intend to continue the dialogue. I asked for no emotions, you tried to push them, that's all.

If you suddenly speak Russian, read the telegram channel "Война с фейками". There they provide evidence of everything that is going on at this time

And yes, the bombing in Mariupol is a fake and there is proof of it on the Internet. More precisely, about who arranged this bombing.

And here is another fake from Ukraine

https://en.topwar.ru/193319-fejk-o-bombardirovke-mariupolja-vojskami-rf-s-uchastiem-beremennoj-modeli-byl-razoblachen.html

I think you've seen these photos in your news feed with loud headlines - Russia kills children (Or something like that :) )

Time will judge us.

**Comment by sokil** [comment]
![hqdefault](https://user-images.githubusercontent.com/1829948/158890142-0ca627fb-0d49-4728-ace9-1b292b50ab28.jpg)

**Comment by ap10111997** [comment]
I didn't doubt it)))

**Comment by Borowing** [comment]
@ap10111997 Yeah, of course, bombing Ukraine is a big fake))))

**Comment by Borowing** [comment]
@ap10111997 Yeah, all russians that gonna occupy us will be dead, simple

**Comment by Borowing** [comment]
@ap10111997 russia admitted that it bombed the hospital in Mariupol, didn't it?

**Comment by Borowing** [comment]
oh, it is the same as with boeng-mh17 in 14 - everything but not russian бук

**Comment by rupower** [comment]
> @ap10111997 russia admitted that it bombed the hospital in Mariupol, didn't it?

https://www.youtube.com/shorts/-59sb08U2Yw - A resident of Mariupol talks about the "valiant" Ukrainian soldiers
https://www.youtube.com/watch?v=cJrBnFfsa8o - A local resident from Mariupol talks about the atrocities of the Ukrainian Armed Forces
https://www.youtube.com/watch?v=cS4hyiLqM4Q - A resident of Mariupol tells how Ukrainian soldiers use civilians as human shields
https://www.youtube.com/watch?v=r8e9SyONhsY - A resident of Mariupol tells who and why is actually shelling Mariupol
https://www.youtube.com/watch?v=s6MVtjEcH-8 - Mariupol Humanitarian corridor: who does not let people out. Please read comments under video
