### ISSUE TITLE
You do not know who you attack

### ISSUE THREAD

**Issue by greatvovan** [RIAEvangelist/peacenotwar#48]
It may be a hospital, a charity fund, a human rights organization, etc. You harm the forces that act against the war.

**Comment by Borowing** [comment]
russia and Belarus are attacking Ukraine right now - so it's gonna help to stop war as soon as possible

**Comment by RIAEvangelist** [comment]
There was no attack. The people saying there were are just trying to stir up drama to avoid taking responsibility for not managing their packages. look at the peacenotwar module and review its actual code.

**Comment by Mehvix** [comment]
[archives don't lie. archives are forever.](https://archive.ph/FOfyF)

**Comment by Aspie96** [comment]
@Borowing HOW?

How will it help stop the war?
