### ISSUE TITLE
This is so racist.

### ISSUE THREAD

**Issue by BrandonHuu** [RIAEvangelist/peacenotwar#50]
Imagine being such a racist piece of shit you decide to attack random people in Russia when they are already suffering.

They lost their entire retirement, the entire world is attacking them for something their government did. They lost access to their bank accounts and some are probably starving to death because they cant buy food. 

And during all of this some random jack ass decides "Let me delete all their important files".
Imagine deleting videos & pictures of someones family for something they had nothing to do with.

You are disgusting, i hope you rot in prison

**Comment by tahir-hassan** [comment]
Exactly, don't harm ordinary people for the actions of their government.
