### ISSUE TITLE
Get off your high horse you POS

### ISSUE THREAD

**Issue by Ebosch747** [RIAEvangelist/peacenotwar#51]
I can't believe you think this would be an ok thing to do. It would be one thing if you just left an annoying little peace text file on people's desktops and left it at that, but no. Nuking the computers of Russian citizens who don't have anything to do with what's going on and are already suffering from the actions of Vladimir Putin will not solve anything. You are actively making the lives of the people you are protesting for worse. I hope you lose all of your credibility as a developer, in your professional life and in the open source community.  I'm going to report you in hopes that you will be banned from GitHub, and I hope others follow suit.

**Comment by Titaniumtown** [comment]
Yea. good luck for him getting a job in the future lmfao. he's fucked
