### ISSUE TITLE
You’re actually a horrible person.

### ISSUE THREAD

**Issue by t3xasdev** [RIAEvangelist/peacenotwar#53]
Way to go. Not only are you affecting the lives of innocent Russian civilians who’s lives are already ruined by their stupid government but you’ve also put a big ripple in not just me but dozens if not thousands of others trust in the Open-Source community. Why the hell would you let your ideology get into the work and destroy your credibility as a whole man? Makes no sense but you made this choice not us.

**Comment by Titaniumtown** [comment]
Literally. what a fucking asshole.

**Comment by t3xasdev** [comment]
> Literally. what a fucking asshole.

Exactly he has as well said “thanks for the PR but your merge won’t be added” which clearly shows he doesn’t give a shit about innocent Russian civilians. He’s actually destroying the lives of civilians who probably disagree with Putin on the war anyway.

**Comment by AIndoria** [comment]
The dev probably also supports the Japanese internment in WW2 because "Pearl harbor lives were important and we absolutely need to target civilians!"

**Comment by cloud65** [comment]
He forgot that he belonged to a nation that burned Vietnamese villages with napalm.
