### ISSUE TITLE
“WITH-LOVE-FROM-AMERICA” ，is this funny ?

### ISSUE THREAD

**Issue by shycool** [RIAEvangelist/peacenotwar#6]
"War is not the answer", I agree it.
Also i don't support russia.
Can America Represent Peace?
America has waged the most wars since 1945.
Korean War 1950-1953
Lebanon 1958
Vietnam War 1961-1975
Grenada 1983
Libya 1986
Panama 1989-1990
The Gulf War 1991
Kosovo war 1999
Afghanistan War 2001-2014
Second Gulf War 2003-2011
and so on.

Is it the love of America ?

**Comment by RIAEvangelist** [comment]
No, I am in America, so the message is with love from me in America, not from America the country.

Valid points. We should stand against all war, even American war.
