### ISSUE TITLE
"Software developers" with the brains of a high schooler - pathetic

### ISSUE THREAD

**Issue by dheeraj-326** [RIAEvangelist/peacenotwar#73]
Pathetic. You are stupid. Nothing more to say.

**Comment by josephworks** [comment]
I'm a highschooler btw and myself and a few dozen others (after discussion on discord obviously) do not condone this repository or the developers recent behavior. Check with the middle-schoolers maybe?

**Comment by dheeraj-326** [comment]
Any system runs on trust. Ruin it and there is no going back. The immature overreactions we see now will have medium to long term consequences, most likely to the detriment of the west.

**Comment by dheeraj-326** [comment]
> I'm a highschooler btw and myself and a few dozen others (after discussion on discord obviously) do not condone this repository or the developers recent behavior. Check with the middle-schoolers maybe?

It is Russian civilians who are affected by your hacktivism. But please also take a look at my other comment which looks at the bigger picture.
